version: '3.6'

services:

    scheduler:
        image: skasip/dprepb-c-pipeline
        ports:
            - 8786:8786
            - 8787:8787   
        expose:
            - "2181"
            - "9092"
        entrypoint: ["bash", "./SKA-SIP-DPrepB-C-Pipeline/docker-entrypoint.sh"]
        build:
            context: .
        volumes: 
            - type: bind
              source: /mnt/ceph/dprepb-c/SKA-SIP-DPrepB-C-Pipeline/inputs-docker
              target: /data/inputs
            - type: bind
              source: /mnt/ceph/dprepb-c/SKA-SIP-DPrepB-C-Pipeline/outputs-docker
              target: /data/outputs


    worker:
        image: skasip/dprepb-c-pipeline
        hostname: dask-worker
        command: ["dask-worker", "--memory-limit 32000000000 --resources MEM=32000000000 scheduler:8786"]
        build:
            context: .
        expose:
            - "2181"
            - "9092"
        volumes: 
            - type: bind
              source: /mnt/ceph/dprepb-c/SKA-SIP-DPrepB-C-Pipeline/outputs-docker
              target: /data/outputs


    notebook:
        image: skasip/dprepb-c-pipeline
        hostname: notebook
        ports:
            - 8888:8888
        expose:
            - "2181"
            - "9092"
        build:
            context: .
        volumes: 
            - type: bind
              source: /mnt/ceph/dprepb-c/SKA-SIP-DPrepB-C-Pipeline/inputs-docker
              target: /data/inputs
            - type: bind
              source: /mnt/ceph/dprepb-c/SKA-SIP-DPrepB-C-Pipeline/outputs-docker
              target: /data/outputs


    qa:
        image: skasip/dprepb-c-qa-aggregator
        hostname: qa
        expose:
            - "2181"
            - "9092"
        build:
            context: .
            dockerfile: Dockerfile.qa
        tty: true

